### ISSUE TITLE
About GES-GSP

### ISSUE THREAD

**Issue by mldemox** [RussRobin/OBJ-GSP#1] opened 2024-07-01 12:26 UTC
Thank you for your outstanding work, recently I am investigating image stitching domain methods, can you please provide the code for the GES-GSP method? I see that there is a comparison in your paper.

**Comment by RussRobin** [comment] 2024-07-01 12:31
Thanks for your interest! The authors of GES-GSP provide official code [here](https://github.com/flowerDuo/GES-GSP-Stitching).

**Comment by mldemox** [comment] 2024-07-01 13:20
But the official code compiles with various files missing, have you successfully reproduced its code?

**Comment by RussRobin** [comment] 2024-07-01 13:48
Just to clarify that I don’t work for GES-GSP and is not responsible for debugging and reimplementing it.

You may want to follow instructions in this repo to install OBJ-GSP and set const int RUN_TYPE = 1; in Configure.h to get GES-GSP results. I add some own implementations in OBJ-GSP to reproduce GES-GSP, and experimental results show that my implementation is almost the same with those reported in GES-GSP paper.

Feel free to further comment on this issue if you still have problems about OBJ-GSP.

**Comment by mldemox** [comment] 2024-07-02 02:03
Understood. Thank you for your response.

**Comment by mldemox** [comment] 2024-07-04 11:24
![图片](https://github.com/RussRobin/OBJ-GSP/assets/141338292/7c34a4ba-625f-4301-a8e2-46d78704781e)
May I ask how to deal with this issue?

**Comment by RussRobin** [comment] 2024-07-04 11:30
May you please provide:
Which version of VS are you using?
Have you compiled opencv 4.4.0 correct? Is there any missing dlls?

**Comment by RussRobin** [comment] 2024-07-04 11:32
Also, please check Event-Post build event in VS

**Comment by mldemox** [comment] 2024-07-04 11:44
I am using VS 2019 and recompiled opencv, opencv_contrib.

**Comment by RussRobin** [comment] 2024-07-17 07:09
I'll close this issue since there's no further discussion for 2 weeks. Feel free to reopen it if you still have concerns about the implementation about OBJ-GSP.

**Closed as completed by RussRobin** 2024-07-17 07:09 UTC
